import { createTheme, ThemeProvider } from "@mui/material"
import Head from "next/head"
import Header from "./Header/Header"
import Footer from "./Footer/Footer"

const THEME = createTheme({
    typography: {
        fontFamily: `"Mulish","Roboto", "Helvetica", "Arial", sans-serif`,
    },
    palette: {
        text: {
            primary: "rgb(136, 136, 136)",
        },
    },
})

export default function Layout({ children }) {
    return (
        <ThemeProvider theme={THEME}>
            <Head>
                <title>SERVBUD</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div>
                {children}
            </div>
            <Footer />
        </ThemeProvider>
    )
}
